var result1 = "hello".includes("e").toUpperCase(); // Invalid beacuse include method returns boolean and booleans do not have .toUpperCase().
var result2 = "world".indexOf("o").concat("cean"); // Invalid beacuse indexOf method returns number.
var result3 = "goodbye".endsWith("e").replace("e", "a"); // Invalid. .endsWith() shows boolean and doesn't support replace method.
var result4 = "example".slice(0, 3).indexOf("a"); // Valid. Both methods return string.
var result5 = "space".trimStart().trimEnd().toUpperCase().slice(-1).toLowerCase(); // Valid. All methods work.
var result6 = "boolean".startsWith("b").toString().replace("true", "yes"); // 
var result7 = "JavaScript".toLowerCase().trim().concat(" is fun"); // Valid. Returns string.
var result8 = "Learning".slice(0, 4).toUpperCase().endsWith("N"); // 
var result9 = " Hello, World! ".trim().replace("World", "Everyone"); // Valid. Returns string.
var result10 = "Data".concat(" Analysis").trimStart().toLowerCase(); // Valid. Returns string.
var result11 = "Search".indexOf("e").toString().slice(0, 1); // Valid.
var result12 = "coding".toUpperCase().startsWith("C"); // Valid. Returns string.
var result13 = "text".toUpperCase().includes(5); // Valid.
var result14 = "number".indexOf("n").startsWith("0"); // Invalid. indexOf returns a number.
var result15 = "trim".trimEnd().length.concat(" characters"); // Invalid. Length returns number.
var result16 = "ReplaceAll".replaceAll("l", "ll").indexOf("ll").toString().trim(); // Valid.
var result17 = "find me".toUpperCase().includes("FIND"); // Valid. 
var result18 = " space ".trim().trimStart().trimEnd().length.toString(); // 
var result19 = "EndsWith".toLowerCase().endsWith("swith"); // Valid. 
var result20 = "multiple words".slice(0, 8).trim().toUpperCase(); // Valid. Returns string.